# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: amiedes.tech
description: > # this means to ignore newlines until "baseurl:"
  Blog/página personal de Alberto Miedes.
baseurl: "" # the subpath of your site, e.g. /blog

# Cambiar esto en función de si estoy trabajando en localhost o en el sitio publicado
url: "http://amiedes.tech" # the base hostname & protocol for your site
#url: "http://localhost"

twitter_username: albertomg994
github_username:  albertomg994
linkedin_username: amiedes

# Build settings
markdown: kramdown

# Outputting
permalink: date
